# -*- coding: utf-8 -*-



network_distribution = {
	"Swisscom": 55, 
	"Sunrise": 27, 
	"Salt": 18,
	"Swisscom Mobile":0,
	"Salt":0,
	"Sunrise Mobile":0,
	"M-Budget":0,
	"Coop Mobile":0,
	"Aldi":0,
	"ok.-":0,
	"Lebara":0,
	"TalkTalk Mobile / Fix":0,
	"Yallo":0,
	"Lycamobile":0,
	"Ortel":0,
	"upc Mobile":0
}


country_prefixes = {
"+1": "USA",
"+20" : "Ägypten",
"+212" : "Marokko",
"+213" : "Algerien",
"+216" : "Tunesien",
"+218" : "Libyen",
"+220" : "Gambia",
"+221" : "Senegal",
"+222" : "Mauretanien",
"+223" : "Mali",
"+224" : "Guinea",
"+225" : "Côte d'Ivoire",
"+226" : "Burkina Faso (Obervolta)",
"+227" : "Niger",
"+228" : "Togo",
"+229" : "Benin",
"+230" : "Mauritius",
"+231" : "Liberia",
"+232" : "Sierra Leone",
"+233" : "Ghana",
"+234" : "Nigeria",
"+235" : "Tschad",
"+236" : "Zentralafrikanische Republik",
"+237" : "Kamerun",
"+238" : "Kap Verde",
"+240" : "Äquatorialguinea",
"+241" : "Gabun",
"+242" : "Kongo (Republik)",
"+243" : "Kongo (Dem. Republik)",
"+244" : "Angola",
"+245" : "Guinea-Bissau",
"+247" : "Ascension",
"+248" : "Seychellen",
"+249" : "Sudan",
"+250" : "Ruanda",
"+251" : "Äthiopien",
"+252" : "Somalia",
"+253" : "Dschibuti",
"+254" : "Kenia",
"+255" : "Tansania",
"+256" : "Uganda",
"+257" : "Burundi",
"+258" : "Mosambik",
"+260" : "Sambia",
"+261" : "Madagaskar",
"+263" : "Simbabwe",
"+264" : "Namibia",
"+265" : "Malawi",
"+266" : "Lesotho",
"+267" : "Botswana",
"+268" : "Swasiland",
"+269" : "Komoren",
"+27" : "Südafrika",
"+291" : "Eritrea",
"+297" : "Aruba",
"+298" : "Färöer",
"+299" : "Grönland",
"+30" : "Griechenland",
"+31" : "Niederlande",
"+32" : "Belgien",
"+33" : "Frankreich",
"+34" : "Spanien",
"+350" : "Gibraltar",
"+351" : "Portugal",
"+352" : "Luxemburg",
"+353" : "Irland",
"+354" : "Island",
"+355" : "Albanien",
"+356" : "Malta",
"+357" : "Zypern",
"+358" : "Finnland",
"+359" : "Bulgarien",
"+36" : "Ungarn",
"+370" : "Litauen",
"+371" : "Lettland",
"+372" : "Estland",
"+373" : "Moldawien",
"+374" : "Armenien",
"+375" : "Weißrussland",
"+376" : "Andorra",
"+377" : "Monaco",
"+378" : "San Marino",
"+380" : "Ukraine",
"+381" : "Serbien",
"+382" : "Montenegro",
"+385" : "Kroatien",
"+386" : "Slowenien",
"+387" : "Bosnien und Herzegowina",
"+389" : "Mazedonien",
"+39" : "Italien",
"+40" : "Rumänien",
"+420" : "Tschechien",
"+421" : "Slowakei",
"+423" : "Liechtenstein",
"+43" : "Österreich",
"+44" : "Vereinigtes Königreich",
"+45" : "Dänemark",
"+47" : "Norwegen",
"+48" : "Polen",
"+49" : "Deutschland",
"+500" : "Falklandinseln",
"+501" : "Belize",
"+502" : "Guatemala",
"+503" : "El Salvador",
"+504" : "Honduras",
"+505" : "Nicaragua",
"+506" : "Costa Rica",
"+507" : "Panama",
"+509" : "Haiti",
"+51" : "Peru",
"+52" : "Mexiko",
"+53" : "Kuba",
"+54" : "Argentinien",
"+55" : "Brasilien",
"+56" : "Chile",
"+57" : "Kolumbien",
"+58" : "Venezuela",
"+590" : "Guadeloupe",
"+591" : "Bolivien",
"+592" : "Guyana",
"+593" : "Ecuador",
"+594" : "Französisch-Guayana",
"+595" : "Paraguay",
"+596" : "Martinique",
"+597" : "Suriname",
"+598" : "Uruguay",
"+60" : "Malaysia",
"+61" : "Australien",
"+62" : "Indonesien",
"+63" : "Philippinen",
"+64" : "Neuseeland",
"+65" : "Singapur",
"+66" : "Thailand",
"+673" : "Brunei",
"+674" : "Nauru",
"+675" : "Papua-Neuguinea",
"+676" : "Tonga",
"+677" : "Salomonen",
"+678" : "Vanuatu",
"+679" : "Fidschi",
"+680" : "Palau",
"+681" : "Wallis & Futuna Islands",
"+682" : "Cookinseln",
"+683" : "Niue",
"+685" : "Samoa",
"+686" : "Kiribati",
"+687" : "Neukaledonien",
"+688" : "Tuvalu",
"+690" : "Tokelau",
"+691" : "Mikronesien",
"+692" : "Marshallinseln",
"+7" : "Kasachstan ",
"+7" : "Russland ",
"+81" : "Japan",
"+84" : "Vietnam",
"+852" : "Hongkong",
"+855" : "Kambodscha",
"+856" : "Laos",
"+86" : "China",
"+880" : "Bangladesch",
"+90" : "Türkei",
"+91" : "Indien",
"+92" : "Pakistan",
"+93" : "Afghanistan",
"+94" : "Sri Lanka",
"+95" : "Myanmar",
"+960" : "Malediven",
"+961" : "Libanon",
"+962" : "Jordanien",
"+963" : "Syrien",
"+964" : "Irak",
"+965" : "Kuwait",
"+966" : "Saudi-Arabien",
"+967" : "Jemen",
"+968" : "Oman",
"+970" : "Palästinensische Aut.-gebiete",
"+971" : "Vereinigte Arabische Emirate",
"+972" : "Israel",
"+973" : "Bahrain",
"+974" : "Katar",
"+976" : "Mongolei",
"+977" : "Nepal",
"+98" : "Iran",
"+992" : "Tadschikistan",
"+993" : "Turkmenistan",
"+994" : "Aserbaidschan",
"+995" : "Georgien)",
"+996" : "Kirgisistan",
"+998" : "Usbekistan"
}



german = [
"Polen",
"Deutschland",
"Oman",
"Vereinigtes Königreich",
"Dänemark",
"Irak",
"Norwegen",
"Rumänien",
"Syrien",
"Malediven",
"Österreich",
"Kongo (Dem. Republik)",
"Kongo (Republik)",
"Gabun",
"Äquatorialguinea",
"Ascension",
"Guinea-Bissau",
"Angola",
"Sudan",
"Seychellen",
"Thailand",
"Neuseeland",
"Singapur",
"Indonesien",
"Philippinen",
"Malaysia",
"Australien",
"Libyen",
"Tunesien",
"Marokko",
"Algerien",
"Uruguay",
"Ecuador",
"Guyana",
"Bolivien",
"Guadeloupe",
"Suriname",
"Martinique",
"Paraguay",
"Französisch-Guayana",
"Tokelau",
"Mikronesien",
"Marshallinseln",
"Falklandinseln",
"Belize",
"Guatemala",
"El Salvador",
"Honduras",
"Nicaragua",
"Costa Rica",
"Panama",
"Madagaskar",
"Haiti",
"Simbabwe",
"Malawi",
"Namibia",
"Botswana",
"Eritrea",
"Kuwait",
"Jordanien",
"Albanien",
"Island",
"Japan",
"Libanon",
"Vietnam",
"Zypern",
"China",
"Malta",
"Färöer",
"Grönland",
"Irland",
"Luxemburg",
"Kap Verde",
"Sierra Leone",
"Ghana",
"Mauritius",
"Liberia",
"Zentralafrikanische Republik",
"Kamerun",
"Nigeria",
"Tschad",
"Spanien",
"Ungarn",
"Niederlande",
"Griechenland",
"Frankreich",
"Belgien",
"Italien",
"Iran",
"Komoren",
"Swasiland",
"Bangladesch",
"Sambia",
"Venezuela",
"Kolumbien",
"Chile",
"Brasilien",
"Argentinien",
"Kuba",
"Mexiko",
"Peru",
"Liechtenstein",
"Slowakei",
"Tschechien",
"Lesotho",
"Brunei",
"Tonga",
"Salomonen",
"Nauru",
"Papua-Neuguinea",
"Vanuatu",
"Fidschi",
"Ruanda",
"Äthiopien",
"Somalia",
"Dschibuti",
"Kenia",
"Tansania",
"Uganda",
"Burundi",
"Mosambik",
"Monaco",
"Andorra",
"Weißrussland",
"Armenien",
"Moldawien",
"Estland",
"Lettland",
"Litauen",
"San Marino",
"Vereinigte Arabische Emirate",
"Palästinensische Aut.-gebiete",
"Bahrain",
"Israel",
"Katar",
"Nepal",
"Mongolei",
"Saudi-Arabien",
"Kirgisistan",
"Georgien)",
"Aserbaidschan",
"Turkmenistan",
"Tadschikistan",
"Usbekistan",
"Jemen",
"Aruba",
"Bulgarien",
"Finnland",
"Afghanistan",
"Pakistan",
"Indien",
"Türkei",
"Portugal",
"Gibraltar",
"Myanmar",
"Sri Lanka",
"Laos",
"Kambodscha",
"Hongkong",
"USA",
"Russland ",
"Niue",
"Cookinseln",
"Wallis & Futuna Islands",
"Palau",
"Neukaledonien",
"Kiribati",
"Samoa",
"Tuvalu",
"Ägypten",
"Südafrika",
"Mauretanien",
"Benin",
"Côte d'Ivoire",
"Guinea",
"Niger",
"Burkina Faso (Obervolta)",
"Senegal",
"Gambia",
"Mali",
"Mazedonien",
"Slowenien",
"Bosnien und Herzegowina",
"Kroatien",
"Montenegro",
"Togo",
"Ukraine",
"Serbien", 
"Schweiz"]


english = [
"Poland",
"Germany",
"Oman",
"United Kingdom",
"Denmark",
"Iraq",
"Norway",
"Romania",
"Syria",
"Maldives",
"Austria",
"Congo (Dem. Republic)",
"Congo (Republic of)",
"Gabon",
"Equatorial Guinea",
"Ascension",
"Guinea-Bissau",
"angola",
"sudan",
"Seychelles",
"Thailand",
"New Zealand",
"Singapore",
"Indonesia",
"Philippines",
"Malaysia",
"Australia",
"Libya",
"Tunisia",
"Morocco",
"Algeria",
"Uruguay",
"Ecuador",
"Guyana",
"Bolivia",
"Guadeloupe",
"Suriname",
"Martinique",
"Paraguay",
"French Guiana",
"Tokelau",
"Micronesia",
"Marshall Islands",
"Falkland Islands",
"Belize",
"Guatemala",
"El Salvador",
"Honduras",
"Nicaragua",
"Costa Rica",
"Panama",
"Madagascar",
"Haiti",
"Zimbabwe",
"Malawi",
"Namibia",
"Botswana",
"Eritrea",
"Kuwait",
"Jordan",
"Albania",
"Iceland",
"Japan",
"Lebanon",
"Vietnam",
"Cyprus",
"China",
"Malta",
"Faroe",
"Greenland",
"Ireland",
"Luxembourg",
"Cape Verde",
"Sierra Leone",
"Ghana",
"Mauritius",
"Liberia",
"Central African Republic",
"Cameroons",
"Nigeria",
"Chad",
"Spain",
"Hungary",
"Netherlands",
"Greece",
"France",
"Belgium",
"Italy",
"Iran",
"Comoros",
"Swaziland",
"Bangladesh",
"Zambia",
"Venezuela",
"Colombia",
"Chile",
"Brazil",
"Argentina",
"Cuba",
"Mexico",
"Peru",
"Liechtenstein",
"Slovakia",
"Czech Republic",
"Lesotho",
"Brunei",
"Tonga",
"Solomon Islands",
"Nauru",
"Papua New Guinea",
"vanuatu",
"Fiji",
"Rwanda",
"Ethiopia",
"Somalia",
"Djibouti",
"Kenya",
"Tanzania",
"Uganda",
"Burundi",
"Mozambique",
"monaco",
"Andorra",
"Belarus",
"Armenia",
"Moldova",
"Estonia",
"Latvia",
"Lithuania",
"San Marino",
"United Arab Emirates",
"Palestinian aut-areas",
"bahrain",
"Israel",
"Qatar",
"Nepal",
"Mongolia",
"Saudi Arabia",
"Kyrgyzstan",
"Georgia",
"Azerbaijan",
"turkmenistan",
"Tajikistan",
"Uzbekistan",
"Yemen",
"aruba",
"Bulgaria",
"Finland",
"Afghanistan",
"Pakistan",
"India",
"Turkey",
"Portugal",
"Gibraltar",
"Myanmar",
"Sri Lanka",
"Laos",
"Cambodia",
"Hong Kong",
"USA",
"Russia",
"Niue",
"Cook Islands",
"Wallis & Futuna Islands",
"Palau",
"Caledonia",
"kiribati",
"Samoa",
"Tuvalu",
"Egypt",
"South Africa",
"Mauritania",
"Benin",
"Côte d'Ivoire",
"Guinea",
"Niger",
"Burkina Faso (Upper Volta)",
"Senegal",
"Gambia",
"Mali",
"Macedonia",
"Slovenia",
"Bosnia and Herzegovina",
"Croatia",
"Montenegro",
"Togo",
"Ukraine",
"Serbia",
"Switzerland"
]


translation_table  = {}

for i in range(0, len(english)):
	translation_table[english[i]] = german[i]
